# Generated by Django 3.2.4 on 2021-06-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='featuredpls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default='', max_length=100)),
                ('title1', models.CharField(default='title1', max_length=50)),
                ('title2', models.CharField(default='title2', max_length=100)),
                ('desc', models.TextField(default='description', max_length=500)),
            ],
        ),
    ]
