# Generated by Django 3.2.4 on 2021-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_featuredpls_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentProj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='Pictures', upload_to='Pictures')),
            ],
        ),
    ]
