# Generated by Django 3.2.4 on 2021-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_recentproj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentproj',
            old_name='img',
            new_name='Big_image',
        ),
        migrations.AddField(
            model_name='recentproj',
            name='Small_image',
            field=models.ImageField(default='Pictures', upload_to='Pictures'),
        ),
    ]
