# Generated by Django 3.2.4 on 2021-06-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20210627_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='Pictures', upload_to='Pictures', verbose_name='Images')),
                ('Title', models.CharField(default='Title', max_length=100)),
                ('desc', models.TextField(default='Description', max_length=500, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
